export const ADD_BENEFICIARY = "ADD_BENEFICIARY";
export const ADD_BENEFICIARY_REQUEST = "ADD_BENEFICIARY_REQUEST";
export const ADD_BENEFICIARY_SUCCESS = "ADD_BENEFICIARY_SUCCESS";
export const ADD_BENEFICIARY_FAIL = "ADD_BENEFICIARY_FAIL";

export const LIST_BENEFICIARIES_FAIL = "LIST_BENEFICIARIES_FAIL";
export const LIST_BENEFICIARIES_REQUEST = "LIST_BENEFICIARIES_REQUEST";
export const LIST_BENEFICIARIES_SUCCESS = "LIST_BENEFICIARIES_SUCCESS";

export const DELETE_BENEFICIARY_FAIL = "DELETE_BENEFICIARY_FAIL";
export const DELETE_BENEFICIARY_REQUEST = "DELETE_BENEFICIARY_REQUEST";
export const DELETE_BENEFICIARY_SUCCESS = "DELETE_BENEFICIARY_SUCCESS";
