export const ADD_INVOICE_FAIL = "ADD_INVOICE_FAIL";
export const ADD_INVOICE_REQUEST = "ADD_INVOICE_REQUEST";
export const ADD_INVOICE_SUCCESS = "ADD_INVOICE_SUCCESS";

export const LIST_INVOICE_FAIL = "LIST_INVOICE_FAIL";
export const LIST_INVOICE_REQUEST = "LIST_INVOICE_REQUEST";
export const LIST_INVOICE_SUCCESS = "LIST_INVOICE_SUCCESS";

export const DELETE_INVOICE_FAIL = "DELETE_INVOICE_FAIL";
export const DELETE_INVOICE_REQUEST = "DELETE_INVOICE_REQUEST";
export const DELETE_INVOICE_SUCCESS = "DELETE_INVOICE_SUCCESS";
