export const LIST_ORDER_FAIL = "LIST_ORDER_FAIL";
export const LIST_ORDER_REQUEST = "LIST_ORDER_REQUEST";
export const LIST_ORDER_SUCCESS = "LIST_ORDER_SUCCESS";

export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";
export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
